language: rust
cache: cargo

rust:
  - stable

os:
  - linux

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
matrix:
  fast_finish: true

script: travis_terminate 1

after_success: echo "After success!!!!!"
